# `user: '${CONTAINERUID}:${CONTAINERGID}'`エントリは`docker:rootless`では必要ない
version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: ${PWD}/container/php/Dockerfile
    container_name: "${PROJECT_NAME}_php-Application_server"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      # <ホストマシンのポート>:<コンテナのポート>
      - 9003:9003
    volumes:
      - ${PWD}/app:/var/www/app
    restart: always
  nginx:
    build:
      context: .
      dockerfile: ${PWD}/container/nginx/Dockerfile
    container_name: ${PROJECT_NAME}-nginx_web_server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:80
    volumes:
      - ${PWD}/app/public:/var/www/app/public
    restart: always
  mariadb:
    image: mariadb:latest
    container_name: ${PROJECT_NAME}_database_server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: ${DB_TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_HOST}:${DB_PORT}:3306
    volumes:
      - ${PWD}/container/mariadb/data:/var/lib/mysql
      - ${PWD}/container/mariadb/initdb.d:/docker-entrypoint-initdb.d
    restart: always
  minio:
    image: minio/minio:latest
    container_name: ${PROJECT_NAME}-object_storage_server
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_ACCESS_KEY}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${MINIO_SECRET_ACCESS_KEY}
    entrypoint: bash
    volumes:
      - ${PWD}/container/minio/data:/data
      - ${PWD}/container/minio/export:/export
      - ${PWD}/container/minio/config:/root/.minio
      - ${PWD}/container/minio/policies:/policies
      - ${PWD}/container/minio/create_backet.sh:/bin/create_backet.sh
    restart: always
    command: -c "sh /bin/create_backet.sh"
networks:
  app_net:
    name: "${PROJECT_NAME}_network"
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24
